### ISSUE TITLE
[Feature Request] Configurable line drop colors

### ISSUE THREAD

**Issue by Unthrottled** [igoriakovlev/JumpToLine#2]
Thanks for the neat plugin!

I was wondering if the plugin's `safe` and `unsafe` dropping line colors could be configured via [JBColor.namedColor](https://github.com/JetBrains/intellij-community/blob/master/platform/util/ui/src/com/intellij/ui/JBColor.java#L63) instead of being hard coded values. That way a theme could potentially supply the color values to be used in-place of the defaults. It doesn't have to be a named color, just as long as it can be configured, that'd be great!

I would be happy to submit a PR if wanted.

**Comment by igoriakovlev** [comment]
Hi Alex!

Waiting forward for your PR's.
Could you please post message here if you going to fix it.

Thank you.

**Comment by Unthrottled** [comment]
@igoriakovlev I'll fix it and submit a PR soon!

**Comment by igoriakovlev** [comment]
0.1.2
