### ISSUE TITLE
Add Action to allow keyboard shortcut

### ISSUE THREAD

**Issue by Gravityzwell** [igoriakovlev/JumpToLine#5]
Idea and PyCharm have "Jump to Cursor" action (in Idea only for Python?).

This allows a keyboard shortcut, jump to line with cursor. This is also how I've used it in Visual Studio for years.

If it's a bad/invalid line, ignore it or log an error.

Great plugin!

**Comment by Gravityzwell** [comment]
Also, Rider has "Skip to Cursor"

**Comment by igoriakovlev** [comment]
0.1.2
