### ISSUE TITLE
Duplicate gutter arrows

### ISSUE THREAD

**Issue by chylex** [igoriakovlev/JumpToLine#8]
I frequently see duplicated gutter arrows when using the plugin:

![obrazek](https://user-images.githubusercontent.com/3685160/131897525-8515120b-a140-43ac-bd13-4538aed0959d.png)

I found out that in `JumpToLineStartupActivity`, `sessionAttached` gets called twice for the same session, so the event listener and gutter renderer gets added twice.

I've not 100% confirmed why this happens, but I suspect it only happens when debugging a Gradle project using a Gradle run configuration. I noticed the debugger gets attached twice in this case, which is visible in the debug log:

```
20:26:58: Executing task ' :runIde'...

Starting Gradle Daemon...
Connected to the target VM, address: '127.0.0.1:55457', transport: 'socket'
Gradle Daemon started in 1 m 11 s 80 ms
> Task :compileKotlin UP-TO-DATE
> Task :compileJava NO-SOURCE
> Task :patchPluginXml UP-TO-DATE
> Task :processResources UP-TO-DATE
> Task :classes UP-TO-DATE
> Task :instrumentCode UP-TO-DATE
> Task :postInstrumentCode
> Task :inspectClassesForKotlinIC UP-TO-DATE
> Task :jar UP-TO-DATE
> Task :prepareSandbox UP-TO-DATE
Disconnected from the target VM, address: '127.0.0.1:55457', transport: 'socket'
Connected to the target VM, address: 'localhost:55515', transport: 'socket'
```

You should be able to reproduce this by debugging an IntelliJ plugin like this one.

**Comment by chylex** [comment]
I fixed this in my branch with commit https://github.com/chylex/IntelliJ-Jump-To-Line/commit/910349341a510db8716f8656282b643fbdf0bf33, if this solution looks ok to you I can PR it.

**Comment by igoriakovlev** [comment]
Thank you for your efforts @chylex.
I made basic implementation for multi-session support, where this bug was fixed with more proper way.
https://github.com/igoriakovlev/JumpToLine/commit/5663692a3c5a028d1698dfb836e10e99327295bf
